conf/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path("", include("ecomapp.urls")),
    path("admin/", admin.site.urls),
    
]

urlpatterns += static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT
)
urlpatterns += static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

ecomapp/urls.py
from django.views.generic import TemplateView
from django.urls import path
from .views import (
    HomeView,
    AboutView,
    ContactView,
    ProductDetailView,
    AddCartView,
    MyCartView,
    ManageCartVie,
    ClearCartView,
    CheckoutView,
    CustomerRegistrationView,
    CustomerLoginView,
    CustomerLogoutView,
    CustomerProfileView,
    CustomerOrderDetailView,
    AdminLogInView,
    AdminHomeView,
    AdminOrderDetailView,
    AdminOrderListView,
    AdminOrderStatusChangeView,
    SearchView,
    KhaltiRequestView,
)

app_name = "ecomapp"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("about/", AboutView.as_view(), name="about-page"),
    path("contact/", ContactView.as_view(), name="contact-page"),
    path("product/<slug:slug>/", ProductDetailView.as_view(), name="product-detail"),
    path("addcart/<int:prod_id>/", AddCartView.as_view(), name="add-cart"),
    path("mycart/", MyCartView.as_view(), name="my-cart"),
    path("manage-cart/<int:cp_id>/", ManageCartVie.as_view(), name="manage-cart"),
    path("empty-cart/", ClearCartView.as_view(), name="empty-cart"),
    path("checkout/", CheckoutView.as_view(), name="checkout"),
    path("khalti-request/", KhaltiRequestView.as_view(), name="khalti_request"),
    path("register/", CustomerRegistrationView.as_view(), name="customerregistration"),
    path("login", CustomerLoginView.as_view(), name="customerlogin"),
    path("logout/", CustomerLogoutView.as_view(), name="logout"),
    path("profile/", CustomerProfileView.as_view(), name="profile"),
    path(
        "profile/order-<int:pk>/",
        CustomerOrderDetailView.as_view(),
        name="order_detail",
    ),
    path("admin-login/", AdminLogInView.as_view(), name="admin_login"),
    path("admin-home", AdminHomeView.as_view(), name="admin_home"),
    path(
        "admin-order/<int:pk>/",
        AdminOrderDetailView.as_view(),
        name="admin_order_detail",
    ),
    path("admin-orders/", AdminOrderListView.as_view(), name="admin_order_list"),
    path(
        "admin-order-<int:pk>-change/",
        AdminOrderStatusChangeView.as_view(),
        name="admin_change_order",
    ),
    path("search/", SearchView.as_view(), name="search"),
]

ecomapp/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.text import slugify


User = get_user_model()


class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=250)
    image = models.ImageField(upload_to="admins")
    mobile = models.CharField(max_length=10)

    def __str__(self):
        return self.user.username


class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title

    def save(self):
        self.slug = slugify(self.title)
        super().save()


class Product(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="products")
    marked_price = models.PositiveIntegerField()
    selling_price = models.PositiveIntegerField()
    description = models.TextField()
    warranty = models.CharField(max_length=300, null=True, blank=True)
    return_policy = models.CharField(max_length=300, null=True, blank=True)
    view_count = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title

    def save(self):
        self.slug = slugify(self.title)
        super().save()


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=200)
    address = models.CharField(max_length=200, null=True, blank=True)
    joined_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name


class Cart(models.Model):
    customer = models.ForeignKey(
        Customer, on_delete=models.SET_NULL, null=True, blank=True
    )
    total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Cart: {self.id}"


class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()

    def __str__(self):
        return f"Cart: {self.cart.id}, CartProduct: {self.id}"


ORDER_STATUS = (
    ("Order Received", "Order Received"),
    ("Order Processing", "Order Processing"),
    ("On the way", "On the way"),
    ("Order Completed", "Order Completed"),
    ("Order Canceled", "Order Canceled"),
)

METHOD = (("Cash On Delivery", "Cash On Delivery"), ("Khalti", "Khalti"))


class Order(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    ordered_by = models.CharField(max_length=200)
    shipping_address = models.CharField(max_length=200)
    mobile = models.CharField(max_length=10)
    email = models.EmailField(null=True, blank=True)
    subtotal = models.PositiveIntegerField()
    discount = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    order_status = models.CharField(max_length=50, choices=ORDER_STATUS)
    created_at = models.DateTimeField(auto_now_add=True)
    payment_method = models.CharField(
        max_length=20, choices=METHOD, default="Cash On delivery"
    )
    payment_completed = models.BooleanField(default=False, null=True, blank=True)

    def __str__(self):
        return f"Order {self.id}"

templates/admin_pages/_admin_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block title %}AdminHome{% endblock %}</title>

     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">

    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

</head>
<body>
   <nav>
    <a href="{% url 'ecomapp:admin_home'%}">Home</a> |
    <a href="{% url 'ecomapp:admin_order_list'%}">All Orders</a> |
    <a href="{% url 'ecomapp:home'%}">View Site</a> |
    <a href="{% url 'ecomapp:admin_login'%}">Login</a>
   </nav>
    <div class="container">
    {% block content %}
    {% endblock %}
</div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/admin_pages/admin_home.html
{% extends './_admin_base.html' %}

{% block title %}
Admin Homepage
{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3>Pending Orders</h3>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Order ID</th>
                        <th>Customer</th>
                        <th>Ordered On</th>
                        <th>Amount</th>
                        
                    </tr>
                    
                </thead>
                <tbody>
                    {% for order in pending_orders%}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td><a href="{% url 'ecomapp:admin_order_detail' order.id %}"> #ORDER_{{order.id}}</a></td>
                        <td>{{order.ordered_by}}</td>
                        <td>{{order.created_at}}</td>
                        <td>{{order.total}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
 
{% endblock %}

templates/admin_pages/admin_login.html
{% extends "_base.html" %}

{% block title %}
Admin Login
{% endblock %}

{% block content %}
<style>
    .errorlist {
    color: red;
}
</style>
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h3>Admin Login Form</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form.as_p}}
                <button class="btn btn-primary">Login as Admin</button>
            </form>
           
        </div>
    </div>
</div>
{% endblock %}

templates/admin_pages/admin_order_detail.html
{% extends '_base.html'%}
{% load humanize %}
{% block title %}
Order Detail
{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 mx-auto">
            <h3>Order Detail</h3><hr>
            <p><span class="fw-bold">Order ID: </span>#Order_{{ord_obj.id}}</p>
            <p><span class="fw-bold">Order Status: </span>#{{ord_obj.order_status}}</p>
            <p><span class="fw-bold">Order On: </span>{{ord_obj.created_at}} ({{ord_obj.created_at|timesince}})</p>
            <p><span class="fw-bold">Customer Information: </span>{{ ord_obj.ordered_by}}, {{ ord_obj.mobile }}</p>
            
            <p><span class="fw-bold">Shipping Address: </span>{{ ord_obj.shipping_address}}, {{ ord_obj.email }}</p>
            <h4>Ordered Items</h4>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Item</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                    </tr>

                </thead>
                <tbody>
                    {% for cp in ord_obj.cart.cartproduct_set.all %}
                        <tr>
                            <td>{{forloop.counter}}</td>
                            <td><a target='_blank' href="{%url 'ecomapp:product-detail' cp.product.slug %}"> {{ cp.product.title}} ({{ cp.product.id}})</a></td>
                            <td>{{ cp.rate }}</td>
                            <td>{{cp.quantity }}</td>
                            <td>{{cp.subtotal}}</td>
                        </tr>
                    {%endfor%}
                    <tr>
                        <th colspan="4" class="text-end">Total:</th>
                        <th>Rs {{ord_obj.total|intcomma}}/.</th>
                    </tr>
                </tbody>
            </table>
            <form action="{% url 'ecomapp:admin_change_order' ord_obj.id %}" method="POST">
                {% csrf_token %}
                <select name="status">
                    {%for i, j in all_status %}
                        <option value="{{i}}" {% if i == ord_obj.order_status %}selected{% endif %}>{{j}}</option>
                    {% endfor %}
                </select>
                <button class="btn btn-info">Change</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/admin_pages/admin_order_list.html
{% extends './_admin_base.html' %}

{% block title %}
All Orders
{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3>Orders</h3>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Order ID</th>
                        <th>Customer</th>
                        <th>Ordered On</th>
                        <th>Amount</th>
                        <th>Status</th>
                        
                    </tr>
                    
                </thead>
                <tbody>
                    {% for order in orders%}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td><a href="{% url 'ecomapp:admin_order_detail' order.id %}"> #ORDER_{{order.id}}</a></td>
                        <td>{{order.ordered_by}}</td>
                        <td>{{order.created_at}}</td>
                        <td>{{order.total}}</td>
                        <td>{{order.order_status}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
 
{% endblock %}