conf/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path("", include("ecomapp.urls")),
    path("admin/", admin.site.urls),
    
]

urlpatterns += static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT
)
urlpatterns += static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

ecomapp/urls.py
from django.views.generic import TemplateView
from django.urls import path
from .views import (
    HomeView,
    AboutView,
    ContactView,
    ProductDetailView,
    AddCartView,
    MyCartView,
    ManageCartVie,
    ClearCartView,
    CheckoutView,
    CustomerRegistrationView,
    CustomerLoginView,
    CustomerLogoutView,
    CustomerProfileView,
    CustomerOrderDetailView,
    AdminLogInView,
    AdminHomeView,
    AdminOrderDetailView,
    AdminOrderListView,
    AdminOrderStatusChangeView,
    SearchView,
    KhaltiRequestView,
)

app_name = "ecomapp"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("about/", AboutView.as_view(), name="about-page"),
    path("contact/", ContactView.as_view(), name="contact-page"),
    path("product/<slug:slug>/", ProductDetailView.as_view(), name="product-detail"),
    path("addcart/<int:prod_id>/", AddCartView.as_view(), name="add-cart"),
    path("mycart/", MyCartView.as_view(), name="my-cart"),
    path("manage-cart/<int:cp_id>/", ManageCartVie.as_view(), name="manage-cart"),
    path("empty-cart/", ClearCartView.as_view(), name="empty-cart"),
    path("checkout/", CheckoutView.as_view(), name="checkout"),
    path("khalti-request/", KhaltiRequestView.as_view(), name="khalti_request"),
    path("register/", CustomerRegistrationView.as_view(), name="customerregistration"),
    path("login", CustomerLoginView.as_view(), name="customerlogin"),
    path("logout/", CustomerLogoutView.as_view(), name="logout"),
    path("profile/", CustomerProfileView.as_view(), name="profile"),
    path(
        "profile/order-<int:pk>/",
        CustomerOrderDetailView.as_view(),
        name="order_detail",
    ),
    path("admin-login/", AdminLogInView.as_view(), name="admin_login"),
    path("admin-home", AdminHomeView.as_view(), name="admin_home"),
    path(
        "admin-order/<int:pk>/",
        AdminOrderDetailView.as_view(),
        name="admin_order_detail",
    ),
    path("admin-orders/", AdminOrderListView.as_view(), name="admin_order_list"),
    path(
        "admin-order-<int:pk>-change/",
        AdminOrderStatusChangeView.as_view(),
        name="admin_change_order",
    ),
    path("search/", SearchView.as_view(), name="search"),
]

ecomapp/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.text import slugify


User = get_user_model()


class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=250)
    image = models.ImageField(upload_to="admins")
    mobile = models.CharField(max_length=10)

    def __str__(self):
        return self.user.username


class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title

    def save(self):
        self.slug = slugify(self.title)
        super().save()


class Product(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="products")
    marked_price = models.PositiveIntegerField()
    selling_price = models.PositiveIntegerField()
    description = models.TextField()
    warranty = models.CharField(max_length=300, null=True, blank=True)
    return_policy = models.CharField(max_length=300, null=True, blank=True)
    view_count = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title

    def save(self):
        self.slug = slugify(self.title)
        super().save()


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=200)
    address = models.CharField(max_length=200, null=True, blank=True)
    joined_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name


class Cart(models.Model):
    customer = models.ForeignKey(
        Customer, on_delete=models.SET_NULL, null=True, blank=True
    )
    total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Cart: {self.id}"


class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()

    def __str__(self):
        return f"Cart: {self.cart.id}, CartProduct: {self.id}"


ORDER_STATUS = (
    ("Order Received", "Order Received"),
    ("Order Processing", "Order Processing"),
    ("On the way", "On the way"),
    ("Order Completed", "Order Completed"),
    ("Order Canceled", "Order Canceled"),
)

METHOD = (("Cash On Delivery", "Cash On Delivery"), ("Khalti", "Khalti"))


class Order(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    ordered_by = models.CharField(max_length=200)
    shipping_address = models.CharField(max_length=200)
    mobile = models.CharField(max_length=10)
    email = models.EmailField(null=True, blank=True)
    subtotal = models.PositiveIntegerField()
    discount = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    order_status = models.CharField(max_length=50, choices=ORDER_STATUS)
    created_at = models.DateTimeField(auto_now_add=True)
    payment_method = models.CharField(
        max_length=20, choices=METHOD, default="Cash On delivery"
    )
    payment_completed = models.BooleanField(default=False, null=True, blank=True)

    def __str__(self):
        return f"Order {self.id}"

templates/_base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <!-- BOOTSTRAP CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">

    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    {% include '_nav.html' %}
    <div class="container">
    {% block content %}
    {% endblock %}
</div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/_nav.html
<style>
  .navbar{
    background-color: rgba(75, 185, 248, 0.932);
    color:white;
  }
</style>
<nav class="navbar navbar-expand-lg">
  <div class="container">
    <a class="navbar-brand" href="#">E-pasal</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'ecomapp:home'%}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'ecomapp:about-page'%}">About</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'ecomapp:contact-page'%}">Contact</a>
        </li>
        
        <li class="nav-item">
          <a class="nav-link" href="{% url 'ecomapp:my-cart'%}">MyCart</a>
        </li>
        
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Electronics Item</a></li>
            <li><a class="dropdown-item" href="#">Clothing and Fashion</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>

        {% if not user.is_authenticated %}
            <li class="nav-item">
          <a class="nav-link" href="#">Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'ecomapp:customerregistration'%}">Register</a>
        </li>
        
        <li class="nav-item">
          <a class="nav-link" href="{% url 'ecomapp:customerlogin'%}">Login</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'ecomapp:profile'%}">Welcome {{user.username}}</a>
        </li>
       
<li class="nav-item">
          <a class="nav-link" href="{% url 'ecomapp:logout'%}">Logout</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'ecomapp:profile'%}">Profile</a>
        </li>
        {% endif%}
        
     
      </ul>
      <form action="{% url 'ecomapp:search' %}" class="d-flex" role="search" method="GET">
        <input class="form-control me-2" type="search" placeholder="Search product here..." aria-label="Search" name="keyword" required>
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

templates/about.html
{% extends '_base.html'%}

{% block title %}
About Page
{% endblock %}

{% block content %}
<style>
    body {
  font-family: Arial, Helvetica, sans-serif;
  margin: 0;
}

html {
  box-sizing: border-box;
}

*, *:before, *:after {
  box-sizing: inherit;
}



.about-section {
  padding: 50px;
  text-align: center;
  background-color: rgba(238, 238, 238, 0.932);
  color: black;
}




</style>
 <div class="about-section container mt-3">
  <h1>About Us Page</h1>
  <p>Some text about who we are and what we do.</p>
  <p>Resize the browser window to see that this page is responsive by the way.</p>
</div>




{% endblock %}
   

templates/c_registration.html
{% extends "_base.html" %}

{% block title %}
Customer Registration
{% endblock %}

{% block content %}
<style>
    .errorlist {
    color: red;
}
</style>
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h3>Customer Registration Form</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form.as_p}}
                <button class="btn btn-primary">Register as a Customer</button>
            </form>
            <p> already registered? <a href="{% url 'ecomapp:customerlogin' %}">Login</a></p>
        </div>
    </div>
</div>
{% endblock %}

templates/cart.html
{% extends '_base.html'%}

{% block title%}Add to Cart {% endblock %}

{% block content %}
<div class="container">
    <h3>Product added to cart successfully</h3>
</div>
{% endblock %}

templates/checkout.html
{% extends '_base.html' %}
{% block title %}
Checkout
{% endblock %}

{% block content%}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h1>Items in the cart </h1>
            <a href="{% url 'ecomapp:my-cart' %}">Update Cart</a>
            <table class="table table-striped table-hover">
               <thead>
                <tr>
                    <th>SN</th>
                    <th>Product</th>
                    <th>Rate</th>
                    <th>Quantity</th>
                    <th>Subtotal</th>
                    <th>Action</th>
                </tr>
               </thead> 
               <tbody>
                {% for cp in cart.cartproduct_set.all %}
                <tr>
                    <td>{{ forloop.counter}}</td>
                    <td>{{ cp.product.title }}</td>
                    <td>{{ cp.rate }}</td>
                    <td>{{ cp.quantity }}</td>
                    <td>{{ cp.subtotal}}</td>
                  
                </tr>

                {% endfor%}
              <tr>
                    <th colspan="4" class="text-end">Total</th>
                    <th >NRs.{{cart.total}}</th>
                    {% if cart.cartproduct_set %}
                    <th><a href="{% url 'ecomapp:empty-cart' %}">Empty Cart</a></th>
                    {% endif%}
                </tr>
              
               </tbody>
            </table>
        </div>
        <div class="col-md-6">
                <h3>Checkout Form</h3>
                <form action="" method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button class="btn btn-info">Place order</button>
                </form>
        </div>
    </div>
</div>

{% endblock content%}

templates/contact.html
{% extends '_base.html'%}

{% block title %}
Contact Page
{% endblock %}
{% block content %}
<style>
    .contact {
  padding: 50px;
  text-align: center;
  background-color: rgba(238, 238, 238, 0.932);
  color: black;

}
</style>
   <div class="container contact mt-3">
    <h1>Contact us</h1>
    <p>9812345678</p>
    <p>9812345454</p>
    <p>ecom@gmail.com</p>
    </div>
{% endblock %}

templates/home.html
{% extends '_base.html'%}

{% block title %}
Home Page
{% endblock %}
{% block content %}
    <h1>We are the emerging ecommerce in City.</h1>

    <div class="row">
    {% for product in page_obj %}
      <div class="col-md-3 card m-1">
        <a href="{% url 'ecomapp:product-detail' product.slug %} " class="text-decoration-none text-dark">
        <div class="img-container  bg-light text-center">
          <img src="{{ product.image.url}}" class="img-fluid" alt="" style="width:200;object-fit:cover;">
        </div>
        <div class="product-data">
          <h3>{{product.title}}</h3>
          <p>Price: <span class="text-decoration-line-through">  Rs.{{ product.marked_price}}</span>  Rs.{{product.selling_price}}</p>
        </div>
        <div>
          <a href="{% url 'ecomapp:add-cart' product.id %}" class="btn btn-primary">Add To Cart</a>
        </div>
  </a>
      </div>
    {% endfor %}

 
<nav class="fixed-bottom">
  <ul class="pagination">
    {% if page_obj.has_previous %}
    <li class="page-item ">
      <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a href="#"  class="page-link">Previous</a>
    </li>
     {% endif%}
{% for i in page_obj.paginator.page_range %}
{% if i == page_obj.number %}
    <li class="page-item active"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
 {% else %}
 <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
 {% endif %}   
 {% endfor %}  
    <!-- <li class="page-item active" aria-current="page">
      <a class="page-link" href="#">2</a>
    </li>
    <li class="page-item"><a class="page-link" href="#">3</a></li> -->
    {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
    </li>
    {%else%}
     <li class="page-item disabled">
      <a class="page-link" href="#">Next</a>
    </li>
    {% endif %}
  </ul>
</nav>
    </div>
{% endblock %}

templates/login.html
{% extends "_base.html" %}

{% block title %}
Customer Login
{% endblock %}

{% block content %}
<style>
    .errorlist {
    color: red;
}
</style>
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h3>Customer Login Form</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form.as_p}}
                <button class="btn btn-primary">Login as a Customer</button>
            </form>
            <p> not registered? <a href="{% url 'ecomapp:customerregistration' %}">Register</a></p>
        </div>
    </div>
</div>
{% endblock %}

templates/my_cart.html
{% extends '_base.html' %}

{% block title%}
    My Cart
{% endblock %}

{%block content %}
<div class="container">
    
    <div class="row">
        <div class="col-md-8">
            {% if cart %}
            <h4>Items in my cart</h4>

            <table class="table table-striped table-hover">
               <thead>
                <tr>
                    <th>SN</th>
                    <th>Product</th>
                    <th>Rate</th>
                    <th>Quantity</th>
                    <th>Subtotal</th>
                    <th>Action</th>
                </tr>
               </thead> 
               <tbody>
                {% for cp in cart.cartproduct_set.all %}
                <tr>
                    <td>{{ forloop.counter}}</td>
                    <td>{{ cp.product.title }}</td>
                    <td>{{ cp.rate }}</td>
                    <td>{{ cp.quantity }}</td>
                    <td>{{ cp.subtotal}}</td>
                    <td>
                        <a href="{% url 'ecomapp:manage-cart' cp.id %}?action=add" class="btn btn-primary">+</a>
                        <a href="{% url 'ecomapp:manage-cart' cp.id %}?action=dec" class="btn btn-warning">-</a>
                        <a href="{% url 'ecomapp:manage-cart' cp.id %}?action=remove" class="btn btn-danger">x</a>
                    </td>
                </tr>
                {% endfor%}
                <tr>
                    <th colspan="4" class="text-end">Total</th>
                    <th >NRs.{{cart.total}}</th>
                    {% if cart.cartproduct_set %}
                    <th><a href="{% url 'ecomapp:empty-cart' %}">Empty Cart</a></th>
                    {% endif %}
                </tr>
               </tbody>
            </table>
            {% else %}
            <h5>Currently there are no items in cart!!</h5>
            {%endif %}
        </div>
    </div>
</div>


{% endblock %}

templates/order_detail.html
{% extends '_base.html'%}
{% load humanize %}
{% block title %}
Order Detail
{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 mx-auto">
            <h3>Order Detail</h3><hr>
            <p><span class="fw-bold">Order ID: </span>#Order_{{ord_obj.id}}</p>
            <p><span class="fw-bold">Order Status: </span>#{{ord_obj.order_status}}</p>
            <p><span class="fw-bold">Order On: </span>{{ord_obj.created_at}} ({{ord_obj.created_at|timesince}})</p>
            <p><span class="fw-bold">Customer Information: </span>{{ ord_obj.ordered_by}}, {{ ord_obj.mobile }}</p>
            
            <p><span class="fw-bold">Shipping Address: </span>{{ ord_obj.shipping_address}}, {{ ord_obj.email }}</p>
            <h4>Ordered Items</h4>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Item</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                    </tr>

                </thead>
                <tbody>
                    {% for cp in ord_obj.cart.cartproduct_set.all %}
                        <tr>
                            <td>{{forloop.counter}}</td>
                            <td><a target='_blank' href="{%url 'ecomapp:product-detail' cp.product.slug %}"> {{ cp.product.title}} ({{ cp.product.id}})</a></td>
                            <td>{{ cp.rate }}</td>
                            <td>{{cp.quantity }}</td>
                            <td>{{cp.subtotal}}</td>
                        </tr>
                    {%endfor%}
                    <tr>
                        <th colspan="4" class="text-end">Total:</th>
                        <th>Rs {{ord_obj.total|intcomma}}/.</th>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

templates/product_detail.html
{% extends '_base.html'%}

{% block title %}Product {% endblock %}

{% block content %}
<div class="container">
    <h3 class="mt-3">Product: {{ product.title }}</h3>
    <div class="row">
        <div class="col-md-6">
            <img src="{{ product.image.url }}" alt="" class="img-fluid">
        </div>
        <div class="col-md-6">
            <div class="product-data">
            <h4>{{ product.title }}</h4>
            <h6>Category: {{ product.category }}</h6>
            <h6>Price:<span class="text-decoration-line-through">  Rs.{{ product.marked_price}}</span>  Rs{{product.selling_price}}</h6>
                <div class="my-3">
                        <a href="{% url 'ecomapp:add-cart' product.id%}" class="btn btn-info">Add To Cart</a>
                </div>
            <hr>
            <p class="text-info">Warrenty: {{ product.warrenty}}</p>
            <p class="text-info">Return Policy: {{ product.return_policy }}</p>
            <hr>
            <p >Description: {{ product.description }}</p> 
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/profile.html
{% extends '_base.html' %}
{% block title %}
Profile
{% endblock %}
{%block content%}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h3>Detail Information </h3>
              <p><span class="font-weight-bold">Name: </span>{{customer.full_name}}</p>
              <p><span class="font-weight-bold">Username: </span>{{customer.user.username}}</p>
              <p><span class="font-weight-bold">Email: </span>{{customer.user.email}}</p>
              <p><span class="font-weight-bold">Address: </span>{{customer.address}}</p>
              <p><span class="font-weight-bold">Joined on: </span>{{customer.joined_on}}</p>
            </div>  
        <div class="col-md-6">
            <h3>Previous Orders</h3>
            <hr>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN:</th>
                        <th>Order ID</th>
                        <th>Amount</th>
                        <th>Ordered on</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    {% for ord in orders %}
                        <tr>
                            <td>{{ forloop.counter}}</td>
                            <td><a href="{% url 'ecomapp:order_detail' ord.id %}">Order_{{ord.id}}</a> </td>
                            <td>{{ ord.total}}</td>
                            <td>{{ ord.created_at|timesince }}</td>
                            <td>{{ ord.order_status }}</td>
                        </tr>
                    {%endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{%endblock %}

templates/search.html
{% extends '_base.html' %}
{%block title %}
Search Results
{%endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3>Search Results for <span class="text-info">"{{request.GET.keyword}}"</span> </h3>
            <hr>
             {% for product in search_results %}
    
      <div class="col-md-3">
        <a href="{% url 'ecomapp:product-detail' product.slug %} " class="text-decoration-none text-dark">
        <div class="img-container bg-light text-center">
          <img src="{{ product.image.url}}" class="img-fluid" alt="" style="width:200;object-fit:cover;">
        </div>
        <div class="product-data">
          <h3>{{product.title}}</h3>
          <p>Price: <span class="text-decoration-line-through">  Rs.{{ product.marked_price}}</span>  Rs.{{product.selling_price}}</p>
        </div>
        <div>
          <a href="{% url 'ecomapp:add-cart' product.id %}" class="btn btn-primary w-100">Add To Cart</a>
        </div>
  </a>
      </div>
      


    {% endfor %}
        </div>
    </div>
</div>
{% endblock %}